"""replace preset icon color with visual key

Revision ID: a053345a5972
Revises: 06407b1d392d
Create Date: 2026-04-04 14:26:58.846416

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a053345a5972"
down_revision: Union[str, Sequence[str], None] = "06407b1d392d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "presets",
        sa.Column(
            "visual_key",
            sa.String(length=100),
            server_default=sa.text("'preset-visual-01'"),
            nullable=False,
        ),
    )
    op.drop_column("presets", "color")
    op.drop_column("presets", "icon")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "presets",
        sa.Column(
            "icon",
            sa.VARCHAR(length=100),
            server_default=sa.text("'default'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "presets",
        sa.Column("color", sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    )
    op.drop_column("presets", "visual_key")
    # ### end Alembic commands ###
