"""create project local mounts table

Revision ID: d17c3fd8fad7
Revises: dc06b3e5d9c5
Create Date: 2026-04-01 22:17:11.936841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd17c3fd8fad7'
down_revision: Union[str, Sequence[str], None] = 'dc06b3e5d9c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_local_mounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('mount_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('host_path', sa.Text(), nullable=False),
    sa.Column('access_mode', sa.String(length=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_project_local_mounts_project_id', 'project_local_mounts', ['project_id'], unique=False)
    op.create_index('ix_project_local_mounts_project_mount_id', 'project_local_mounts', ['project_id', 'mount_id'], unique=True)
    op.execute(
        """
        INSERT INTO project_local_mounts (
            project_id,
            mount_id,
            name,
            host_path,
            access_mode,
            sort_order
        )
        SELECT
            id,
            'project-default',
            COALESCE(NULLIF(BTRIM(mount_name), ''), NULLIF(BTRIM(name), ''), 'Project workspace'),
            BTRIM(mount_path),
            COALESCE(NULLIF(BTRIM(mount_access_mode), ''), 'rw'),
            0
        FROM projects
        WHERE mount_enabled = true
          AND mount_path IS NOT NULL
          AND BTRIM(mount_path) <> ''
        """
    )
    op.drop_column('projects', 'mount_access_mode')
    op.drop_column('projects', 'mount_name')
    op.drop_column('projects', 'mount_path')
    op.drop_column('projects', 'mount_enabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('mount_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('projects', sa.Column('mount_path', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('mount_name', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('mount_access_mode', sa.String(length=2), nullable=True))
    op.execute(
        """
        UPDATE projects
        SET
            mount_enabled = true,
            mount_name = mounts.name,
            mount_path = mounts.host_path,
            mount_access_mode = mounts.access_mode
        FROM (
            SELECT DISTINCT ON (project_id)
                project_id,
                name,
                host_path,
                access_mode
            FROM project_local_mounts
            ORDER BY project_id, sort_order ASC, id ASC
        ) AS mounts
        WHERE projects.id = mounts.project_id
        """
    )
    op.drop_index('ix_project_local_mounts_project_mount_id', table_name='project_local_mounts')
    op.drop_index('ix_project_local_mounts_project_id', table_name='project_local_mounts')
    op.drop_table('project_local_mounts')
    # ### end Alembic commands ###
